### ISSUE TITLE
Social media links not working

### ISSUE THREAD

**Issue by Shybymh** [c4coderandcreator/Flavour-Fusion#6]

**Comment by c4coderandcreator** [comment]
Hello @Shybymh  !! If you want to have a word please reach out to me on social media handles or Discord itself !!

**Comment by Shybymh** [comment]
Hi, I found that the site's social media links are not present. Can I work on it under hacktoberfest?

**Comment by c4coderandcreator** [comment]
@Shybymh that is because this project is under development and there are no official handles as far as of now !! But it will have its social media in future, for now you can redesign it and try adding links within !! Ya I will assign it to you under hacktoberfest , I wish you make your contribution count !!

**Comment by Shybymh** [comment]
This is my first time contributing, thought of starting with small ones. Thanks for assigning!

**Comment by c4coderandcreator** [comment]
That's nice to hear @Shybymh  !! Happy Coding and Welcome to Open source !!
